# Generated by Django 6.0.4 on 2026-04-18 15:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patientId', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('doctorId', models.CharField(max_length=50)),
                ('doctorName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patientId', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('items', models.JSONField()),
                ('totalAmount', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('insuranceCovered', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('head', models.CharField(max_length=100)),
                ('doctorsCount', models.IntegerField(default=0)),
                ('nursesCount', models.IntegerField(default=0)),
                ('bedsTotal', models.IntegerField(default=0)),
                ('bedsOccupied', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('patientsCount', models.IntegerField(default=0)),
                ('experience', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('assignedWard', models.CharField(max_length=100)),
                ('patientsCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('admissionDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('assignedDoctor', models.CharField(max_length=50)),
                ('assignedNurse', models.CharField(max_length=50)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patientId', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('doctorId', models.CharField(max_length=50)),
                ('doctorName', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('medications', models.JSONField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('patientId', models.CharField(max_length=50)),
                ('patientName', models.CharField(max_length=100)),
                ('nurseId', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('bloodPressure', models.CharField(max_length=50)),
                ('heartRate', models.IntegerField()),
                ('oxygenLevel', models.IntegerField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
