# Generated by Django 6.0.4 on 2026-04-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='paymentRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
