# Generated by Django 5.2.13 on 2026-04-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='paidAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='payment_status',
            field=models.CharField(default='Unpaid', max_length=50),
        ),
    ]
